"""
Volatility Indicators - Using precomputed screener_data columns
"""

from typing import List
from .base import IndicatorGroup, IndicatorDefinition, OperatorType, DataType


class VolatilityIndicators(IndicatorGroup):
    """Volatility and range indicators"""
    
    category = "volatility"
    description = "Volatility and price range indicators"
    
    def get_indicators(self) -> List[IndicatorDefinition]:
        standard_ops = [OperatorType.GT, OperatorType.GTE, OperatorType.LT, OperatorType.LTE, OperatorType.BETWEEN]
        
        return [
            IndicatorDefinition(
                name="atr_14",
                display_name="ATR (14)",
                description="14-day Average True Range",
                category=self.category,
                data_type=DataType.FLOAT,
                sql_expression="atr_14",
                operators=standard_ops,
                min_value=0,
                format_string="${:.2f}",
            ),
            IndicatorDefinition(
                name="atr_percent",
                display_name="ATR %",
                description="ATR as percentage of price",
                category=self.category,
                data_type=DataType.PERCENT,
                sql_expression="atr_percent",
                operators=standard_ops,
                min_value=0,
                format_string="{:.2f}%",
            ),
            IndicatorDefinition(
                name="bb_upper",
                display_name="BB Upper",
                description="Bollinger Band Upper (20,2)",
                category=self.category,
                data_type=DataType.FLOAT,
                sql_expression="bb_upper",
                operators=standard_ops,
                format_string="${:.2f}",
            ),
            IndicatorDefinition(
                name="bb_middle",
                display_name="BB Middle",
                description="Bollinger Band Middle (SMA 20)",
                category=self.category,
                data_type=DataType.FLOAT,
                sql_expression="bb_middle",
                operators=standard_ops,
                format_string="${:.2f}",
            ),
            IndicatorDefinition(
                name="bb_lower",
                display_name="BB Lower",
                description="Bollinger Band Lower (20,2)",
                category=self.category,
                data_type=DataType.FLOAT,
                sql_expression="bb_lower",
                operators=standard_ops,
                format_string="${:.2f}",
            ),
            IndicatorDefinition(
                name="bb_width",
                display_name="BB Width %",
                description="Bollinger Band Width as percentage",
                category=self.category,
                data_type=DataType.PERCENT,
                sql_expression="bb_width",
                operators=standard_ops,
                min_value=0,
                format_string="{:.2f}%",
            ),
            IndicatorDefinition(
                name="bb_position",
                display_name="BB Position %",
                description="Price position within BB (0=lower, 100=upper)",
                category=self.category,
                data_type=DataType.PERCENT,
                sql_expression="bb_position",
                operators=standard_ops,
                min_value=0,
                max_value=100,
                format_string="{:.1f}%",
            ),
            IndicatorDefinition(
                name="bb_squeeze",
                display_name="BB Squeeze",
                description="Bollinger Band squeeze (width < 5%) - very low volatility",
                category=self.category,
                data_type=DataType.BOOLEAN,
                sql_expression="CASE WHEN bb_width < 5 THEN 1 ELSE 0 END",
                operators=[OperatorType.EQ],
            ),
            IndicatorDefinition(
                name="above_bb_upper",
                display_name="Above BB Upper",
                description="Price above upper Bollinger Band",
                category=self.category,
                data_type=DataType.BOOLEAN,
                sql_expression="CASE WHEN price > bb_upper THEN 1 ELSE 0 END",
                operators=[OperatorType.EQ],
            ),
            IndicatorDefinition(
                name="below_bb_lower",
                display_name="Below BB Lower",
                description="Price below lower Bollinger Band",
                category=self.category,
                data_type=DataType.BOOLEAN,
                sql_expression="CASE WHEN price < bb_lower THEN 1 ELSE 0 END",
                operators=[OperatorType.EQ],
            ),
            # Keltner Channels
            IndicatorDefinition(
                name="keltner_upper",
                display_name="Keltner Upper",
                description="Keltner Channel Upper (EMA 20 + ATR 10 * 1.5)",
                category=self.category,
                data_type=DataType.FLOAT,
                sql_expression="keltner_upper",
                operators=standard_ops,
                format_string="${:.2f}",
            ),
            IndicatorDefinition(
                name="keltner_middle",
                display_name="Keltner Middle",
                description="Keltner Channel Middle (EMA 20)",
                category=self.category,
                data_type=DataType.FLOAT,
                sql_expression="keltner_middle",
                operators=standard_ops,
                format_string="${:.2f}",
            ),
            IndicatorDefinition(
                name="keltner_lower",
                display_name="Keltner Lower",
                description="Keltner Channel Lower (EMA 20 - ATR 10 * 1.5)",
                category=self.category,
                data_type=DataType.FLOAT,
                sql_expression="keltner_lower",
                operators=standard_ops,
                format_string="${:.2f}",
            ),
            # TTM Squeeze
            IndicatorDefinition(
                name="squeeze_on",
                display_name="TTM Squeeze",
                description="TTM Squeeze ON - BB inside Keltner (low volatility, breakout coming)",
                category=self.category,
                data_type=DataType.BOOLEAN,
                sql_expression="squeeze_on",
                operators=[OperatorType.EQ],
            ),
            IndicatorDefinition(
                name="squeeze_momentum",
                display_name="Squeeze Momentum",
                description="Squeeze momentum - positive = bullish, negative = bearish",
                category=self.category,
                data_type=DataType.FLOAT,
                sql_expression="squeeze_momentum",
                operators=standard_ops,
                format_string="{:.2f}",
            ),
            # ADX (Average Directional Index)
            IndicatorDefinition(
                name="adx_14",
                display_name="ADX (14)",
                description="Average Directional Index - trend strength (>25 = strong trend)",
                category=self.category,
                data_type=DataType.FLOAT,
                sql_expression="adx_14",
                operators=standard_ops,
                min_value=0,
                max_value=100,
                format_string="{:.1f}",
            ),
            IndicatorDefinition(
                name="plus_di_14",
                display_name="+DI (14)",
                description="Positive Directional Indicator",
                category=self.category,
                data_type=DataType.FLOAT,
                sql_expression="plus_di_14",
                operators=standard_ops,
                min_value=0,
                max_value=100,
                format_string="{:.1f}",
            ),
            IndicatorDefinition(
                name="minus_di_14",
                display_name="-DI (14)",
                description="Negative Directional Indicator",
                category=self.category,
                data_type=DataType.FLOAT,
                sql_expression="minus_di_14",
                operators=standard_ops,
                min_value=0,
                max_value=100,
                format_string="{:.1f}",
            ),
            IndicatorDefinition(
                name="adx_trend",
                display_name="ADX Trend",
                description="ADX trend direction: 1=bullish, -1=bearish, 0=no trend",
                category=self.category,
                data_type=DataType.INTEGER,
                sql_expression="adx_trend",
                operators=[OperatorType.EQ, OperatorType.GT, OperatorType.LT],
            ),
            IndicatorDefinition(
                name="strong_uptrend",
                display_name="Strong Uptrend",
                description="ADX > 25 with +DI > -DI (strong bullish trend)",
                category=self.category,
                data_type=DataType.BOOLEAN,
                sql_expression="CASE WHEN adx_14 > 25 AND plus_di_14 > minus_di_14 THEN 1 ELSE 0 END",
                operators=[OperatorType.EQ],
            ),
            IndicatorDefinition(
                name="strong_downtrend",
                display_name="Strong Downtrend",
                description="ADX > 25 with -DI > +DI (strong bearish trend)",
                category=self.category,
                data_type=DataType.BOOLEAN,
                sql_expression="CASE WHEN adx_14 > 25 AND minus_di_14 > plus_di_14 THEN 1 ELSE 0 END",
                operators=[OperatorType.EQ],
            ),
        ]
    
    def get_sql_cte(self) -> str:
        return ""
