#!/bin/bash
# Script de Monitoreo: Ejecución a las 3:00 AM
# Ejecutar ANTES de las 3:00 AM para ver la ejecución en vivo

echo "=========================================="
echo "📊 MONITOREO: Cache Clear System"
echo "=========================================="
echo ""

# Hora actual
echo "🕐 Hora actual (NY):"
TZ=America/New_York date +"%H:%M:%S"
echo ""

# Faltan X minutos
minutos_para_3am=$(( (180 - ($(TZ=America/New_York date +%H) * 60 + $(TZ=America/New_York date +%M))) ))
echo "⏰ Faltan $minutos_para_3am minutos para las 3:00 AM"
echo ""

echo "=========================================="
echo "🔍 OPCIÓN 1: Monitoreo Automático (RECOMENDADO)"
echo "=========================================="
echo ""
echo "Ejecuta en una terminal:"
echo "  watch -n 1 'docker logs tradeul_data_maintenance --since 5m --tail 10 | grep cache_clear'"
echo ""
echo "Verás los logs actualizándose cada segundo."
echo "Cuando ejecute a las 3:00 AM, aparecerán inmediatamente."
echo ""

echo "=========================================="
echo "🔍 OPCIÓN 2: Logs en Tiempo Real (2 terminales)"
echo "=========================================="
echo ""
echo "Terminal 1 - data_maintenance:"
echo "  docker logs -f tradeul_data_maintenance | grep --line-buffered cache_clear"
echo ""
echo "Terminal 2 - websocket_server:"
echo "  docker logs -f tradeul_websocket_server | grep --line-buffered 'Cache cleared'"
echo ""

echo "=========================================="
echo "🔍 OPCIÓN 3: Verificación Post-Ejecución (después de las 3:00)"
echo "=========================================="
echo ""
echo "Ejecutar DESPUÉS de las 3:00 AM:"
echo ""
echo "1. Ver logs data_maintenance:"
echo "   docker logs tradeul_data_maintenance --since 10m --timestamps | grep cache_clear"
echo ""
echo "2. Ver logs websocket_server:"
echo "   docker logs tradeul_websocket_server --since 10m --timestamps | grep 'Cache cleared'"
echo ""
echo "3. Ver Redis keys (deben estar intactas):"
echo "   cd /opt/tradeul && export \$(grep REDIS_PASSWORD .env | xargs) && \\"
echo "   docker exec tradeul_redis redis-cli -a \"\$REDIS_PASSWORD\" --no-auth-warning DBSIZE"
echo ""
echo "4. Ver cache del WebSocket (debe estar vacío después de las 3 AM):"
echo "   # El cache está en memoria de Node.js, no es visible directamente"
echo "   # Pero verás en logs: 'caches_cleared: 100'"
echo ""

echo "=========================================="
echo "🎯 LOGS ESPERADOS A LAS 3:00 AM"
echo "=========================================="
echo ""
echo "data_maintenance (3:00:00):"
echo "  ✅ cache_clear_time_detected time=03:00 AM EST date=2025-11-26"
echo "  ✅ new_day_event_published channel=trading:new_day"
echo "  ✅ cache_clear_executed_successfully"
echo ""
echo "websocket_server (3:00:00):"
echo "  ✅ 🔄 New trading day detected - clearing all caches"
echo "  ✅ Cache cleared for new trading day caches_cleared=100"
echo ""

echo "=========================================="
echo "📋 COMANDOS ÚTILES"
echo "=========================================="
echo ""
echo "Ver hora actual NY:"
echo "  TZ=America/New_York date +\"%H:%M:%S\""
echo ""
echo "Ver últimos logs data_maintenance:"
echo "  docker logs tradeul_data_maintenance --tail 20"
echo ""
echo "Ver últimos logs websocket:"
echo "  docker logs tradeul_websocket_server --tail 20"
echo ""
echo "Contar keys Redis:"
echo "  docker exec tradeul_redis redis-cli -a <pass> DBSIZE"
echo ""
echo "Ver categorías scanner:"
echo "  docker exec tradeul_redis redis-cli -a <pass> KEYS 'scanner:category:*'"
echo ""

