"""Ports (interfaces) for the application layer."""
from __future__ import annotations

from typing import Any, Protocol

from core.models import BacktestResponse


class IJobRepository(Protocol):
    def set_job(self, job_id: str, data: dict[str, Any], ttl_seconds: int | None = None) -> None: ...
    def get_job(self, job_id: str) -> dict[str, Any] | None: ...
    def update_job(self, job_id: str, updates: dict[str, Any]) -> None: ...
    def set_result(self, job_id: str, response: BacktestResponse, ttl_seconds: int | None = None) -> None: ...
    def get_result(self, job_id: str) -> BacktestResponse | None: ...
    def set_error(self, job_id: str, error_message: str, ttl_seconds: int | None = None) -> None: ...


class IJobQueue(Protocol):
    def enqueue(self, job_id: str, payload: dict[str, Any]) -> None: ...
    def dequeue(self, timeout_seconds: int = 0) -> tuple[str, dict[str, Any]] | None: ...
