import {
    FileText, Activity, TrendingUp, BarChart3, ListChecks,
    Newspaper, Users, Calendar, ShieldAlert, Info, Gauge, Target, FlaskConical,
} from 'lucide-react';
import type { WidgetDefinition, CanvasLayout, CanvasTemplate, CanvasConfig, WidgetContext } from '../types';
import {
    ValuationWidget,
    HealthWidget,
    ConsensusWidget,
    ShortInterestWidget,
    TechnicalWidget,
    RatingsWidget,
    NewsWidget,
    InsiderWidget,
    CatalystsWidget,
    RiskWidget,
    AboutWidget,
    QuoteStripWidget,
    ChartWidget,
    DilutionRiskWidget,
} from './widgets';

export const FAN_WIDGETS: WidgetDefinition[] = [
    {
        type: 'quote-strip',
        category: 'overview',
        title: 'Header',
        description: 'Ticker, company, exchange, sector',
        icon: Info,
        component: QuoteStripWidget,
        defaultSize: { w: 12, h: 2 },
        minSize: { w: 6, h: 1 },
        locked: true,
        hiddenFromPalette: true,
    },
    {
        type: 'valuation',
        category: 'fundamentals',
        title: 'Valuation',
        description: 'P/E, EV/EBITDA, P/S, P/B, Div Yield',
        icon: FileText,
        component: ValuationWidget,
        defaultSize: { w: 3, h: 5 },
        minSize: { w: 2, h: 3 },
    },
    {
        type: 'health',
        category: 'fundamentals',
        title: 'Financial Health',
        description: 'Grade, growth, margins, D/E, ROE',
        icon: Activity,
        component: HealthWidget,
        defaultSize: { w: 3, h: 5 },
        minSize: { w: 2, h: 3 },
    },
    {
        type: 'consensus',
        category: 'intel',
        title: 'Consensus',
        description: 'Analyst consensus + price target',
        icon: Target,
        component: ConsensusWidget,
        defaultSize: { w: 3, h: 4 },
        minSize: { w: 2, h: 3 },
    },
    {
        type: 'short-interest',
        category: 'market',
        title: 'Short Interest',
        description: '% float, DTC, squeeze risk',
        icon: Gauge,
        component: ShortInterestWidget,
        defaultSize: { w: 3, h: 4 },
        minSize: { w: 2, h: 3 },
    },
    {
        type: 'technical',
        category: 'technical',
        title: 'Technical',
        description: 'RSI, MAs, support/resistance',
        icon: TrendingUp,
        component: TechnicalWidget,
        defaultSize: { w: 3, h: 5 },
        minSize: { w: 2, h: 3 },
    },
    {
        type: 'ratings',
        category: 'intel',
        title: 'Analyst Ratings',
        description: 'Firm-by-firm ratings table',
        icon: ListChecks,
        component: RatingsWidget,
        defaultSize: { w: 6, h: 5 },
        minSize: { w: 4, h: 3 },
    },
    {
        type: 'news',
        category: 'intel',
        title: 'News',
        description: 'Sentiment + recent headlines',
        icon: Newspaper,
        component: NewsWidget,
        defaultSize: { w: 4, h: 4 },
        minSize: { w: 3, h: 3 },
    },
    {
        type: 'insider',
        category: 'intel',
        title: 'Insider Activity',
        description: 'Recent insider buys/sells',
        icon: Users,
        component: InsiderWidget,
        defaultSize: { w: 3, h: 5 },
        minSize: { w: 2, h: 3 },
    },
    {
        type: 'catalysts',
        category: 'market',
        title: 'Catalysts',
        description: 'Earnings date + upcoming events',
        icon: Calendar,
        component: CatalystsWidget,
        defaultSize: { w: 3, h: 4 },
        minSize: { w: 2, h: 3 },
    },
    {
        type: 'risk',
        category: 'risk',
        title: 'Risk Factors',
        description: 'Risk score + factor list',
        icon: ShieldAlert,
        component: RiskWidget,
        defaultSize: { w: 4, h: 5 },
        minSize: { w: 3, h: 3 },
    },
    {
        type: 'about',
        category: 'overview',
        title: 'About',
        description: 'Business summary',
        icon: Info,
        component: AboutWidget,
        defaultSize: { w: 6, h: 3 },
        minSize: { w: 3, h: 2 },
    },
    {
        type: 'chart',
        category: 'market',
        title: 'Price Chart',
        description: 'Candlestick chart with indicators',
        icon: BarChart3,
        component: ChartWidget,
        defaultSize: { w: 6, h: 7 },
        minSize: { w: 4, h: 5 },
        customHeader: true,
    },
    {
        type: 'dilution-risk',
        category: 'risk',
        title: 'Dilution Risk',
        description: 'Offering, overhead, cash need ratings',
        icon: FlaskConical,
        component: DilutionRiskWidget,
        defaultSize: { w: 3, h: 5 },
        minSize: { w: 2, h: 4 },
    },
];

// Layout que reproduce fielmente el FAN original (no breaking change)
export const FAN_DEFAULT_LAYOUT: CanvasLayout = {
    version: 1,
    items: [
        { i: 'quote-strip-0', type: 'quote-strip', x: 0, y: 0, w: 12, h: 2 },
        { i: 'about-0', type: 'about', x: 0, y: 2, w: 12, h: 3 },
        { i: 'chart-0', type: 'chart', x: 0, y: 5, w: 6, h: 7 },
        { i: 'valuation-0', type: 'valuation', x: 6, y: 5, w: 3, h: 5 },
        { i: 'health-0', type: 'health', x: 9, y: 5, w: 3, h: 5 },
        { i: 'technical-0', type: 'technical', x: 6, y: 10, w: 3, h: 5 },
        { i: 'short-interest-0', type: 'short-interest', x: 9, y: 10, w: 3, h: 4 },
        { i: 'consensus-0', type: 'consensus', x: 0, y: 12, w: 3, h: 4 },
        { i: 'dilution-risk-0', type: 'dilution-risk', x: 3, y: 12, w: 3, h: 5 },
        { i: 'ratings-0', type: 'ratings', x: 0, y: 16, w: 6, h: 5 },
        { i: 'insider-0', type: 'insider', x: 6, y: 15, w: 3, h: 5 },
        { i: 'catalysts-0', type: 'catalysts', x: 9, y: 14, w: 3, h: 4 },
        { i: 'risk-0', type: 'risk', x: 0, y: 21, w: 6, h: 5 },
        { i: 'news-0', type: 'news', x: 6, y: 20, w: 6, h: 5 },
    ],
};

const DAYTRADER_LAYOUT: CanvasLayout = {
    version: 1,
    items: [
        { i: 'quote-strip-dt', type: 'quote-strip', x: 0, y: 0, w: 12, h: 2 },
        { i: 'chart-dt', type: 'chart', x: 0, y: 2, w: 8, h: 7 },
        { i: 'technical-dt', type: 'technical', x: 8, y: 2, w: 4, h: 5 },
        { i: 'short-interest-dt', type: 'short-interest', x: 8, y: 7, w: 4, h: 4 },
        { i: 'news-dt', type: 'news', x: 0, y: 9, w: 4, h: 5 },
        { i: 'insider-dt', type: 'insider', x: 4, y: 9, w: 4, h: 5 },
        { i: 'consensus-dt', type: 'consensus', x: 8, y: 11, w: 4, h: 4 },
    ],
};

const VALUE_LAYOUT: CanvasLayout = {
    version: 1,
    items: [
        { i: 'quote-strip-v', type: 'quote-strip', x: 0, y: 0, w: 12, h: 2 },
        { i: 'valuation-v', type: 'valuation', x: 0, y: 2, w: 4, h: 5 },
        { i: 'health-v', type: 'health', x: 4, y: 2, w: 4, h: 5 },
        { i: 'consensus-v', type: 'consensus', x: 8, y: 2, w: 4, h: 4 },
        { i: 'dilution-risk-v', type: 'dilution-risk', x: 8, y: 6, w: 4, h: 5 },
        { i: 'ratings-v', type: 'ratings', x: 0, y: 7, w: 8, h: 5 },
        { i: 'risk-v', type: 'risk', x: 0, y: 12, w: 6, h: 5 },
        { i: 'about-v', type: 'about', x: 6, y: 12, w: 6, h: 3 },
    ],
};

const EARNINGS_LAYOUT: CanvasLayout = {
    version: 1,
    items: [
        { i: 'quote-strip-e', type: 'quote-strip', x: 0, y: 0, w: 12, h: 2 },
        { i: 'consensus-e', type: 'consensus', x: 0, y: 2, w: 4, h: 4 },
        { i: 'catalysts-e', type: 'catalysts', x: 4, y: 2, w: 4, h: 4 },
        { i: 'short-interest-e', type: 'short-interest', x: 8, y: 2, w: 4, h: 4 },
        { i: 'ratings-e', type: 'ratings', x: 0, y: 6, w: 6, h: 5 },
        { i: 'news-e', type: 'news', x: 6, y: 6, w: 6, h: 5 },
        { i: 'risk-e', type: 'risk', x: 0, y: 11, w: 6, h: 4 },
        { i: 'insider-e', type: 'insider', x: 6, y: 11, w: 6, h: 4 },
    ],
};

export const FAN_TEMPLATES: CanvasTemplate[] = [
    { id: 'default', name: 'Default', description: 'Complete overview — all widgets', layout: FAN_DEFAULT_LAYOUT },
    { id: 'daytrader', name: 'Day Trader', description: 'Technical + news + short interest', layout: DAYTRADER_LAYOUT },
    { id: 'value', name: 'Value Investor', description: 'Fundamentals + ratings + risk', layout: VALUE_LAYOUT },
    { id: 'earnings', name: 'Earnings Play', description: 'Consensus + catalysts + SI', layout: EARNINGS_LAYOUT },
];

export const FAN_CONFIG: CanvasConfig = {
    manifest: { id: 'fan', widgets: FAN_WIDGETS },
    defaultLayout: FAN_DEFAULT_LAYOUT,
    templates: FAN_TEMPLATES,
    cols: 12,
    rowHeight: 28,
};
